on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-alpha[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Echo version
      run: echo ${VERSION}
    - name: Pack
      run: dotnet pack --include-symbols --configuration Release /p:Version=0.0.1-alpha --output .
