on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview-[0-9]+[0-9]+[0-9]"
jobs:
  pre-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Echo version
      run: echo ${VERSION}
    - name: Pack
      run: dotnet pack --include-symbols --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push **/*.nupkg --source https://www.myget.org/F/transformers/api/v2/package --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.MYGET_KEY }}
